export const coinsList: { id: string, name: string, symbol: string }[] = [
    { id: 'bitcoin', name: 'Bitcoin', symbol: 'btc' },
    { id: 'ethereum', name: 'Ethereum', symbol: 'eth' },
    { id: 'tether', name: 'Tether', symbol: 'usdt' },
    { id: 'binancecoin', name: 'BNB', symbol: 'bnb' },
    { id: 'usd-coin', name: 'USD Coin', symbol: 'usdc' },
    { id: 'ripple', name: 'XRP', symbol: 'xrp' },
    { id: 'terra-luna', name: 'Terra', symbol: 'luna' },
    { id: 'solana', name: 'Solana', symbol: 'sol' },
    { id: 'cardano', name: 'Cardano', symbol: 'ada' },
    { id: 'polkadot', name: 'Polkadot', symbol: 'dot' },
    { id: 'avalanche-2', name: 'Avalanche', symbol: 'avax' },
    { id: 'binance-usd', name: 'Binance USD', symbol: 'busd' },
    { id: 'dogecoin', name: 'Dogecoin', symbol: 'doge' },
    { id: 'terrausd', name: 'TerraUSD', symbol: 'ust' },
    { id: 'shiba-inu', name: 'Shiba Inu', symbol: 'shib' },
    { id: 'wrapped-bitcoin', name: 'Wrapped Bitcoin', symbol: 'wbtc' },
    { id: 'crypto-com-chain', name: 'Cronos', symbol: 'cro' },
    { id: 'matic-network', name: 'Polygon', symbol: 'matic' },
    { id: 'dai', name: 'Dai', symbol: 'dai' },
    { id: 'cosmos', name: 'Cosmos Hub', symbol: 'atom' },
    { id: 'litecoin', name: 'Litecoin', symbol: 'ltc' },
    { id: 'near', name: 'Near', symbol: 'near' },
    { id: 'staked-ether', name: 'Lido Staked Ether', symbol: 'steth' },
    { id: 'chainlink', name: 'Chainlink', symbol: 'link' },
    { id: 'tron', name: 'TRON', symbol: 'trx' },
    { id: 'ftx-token', name: 'FTX Token', symbol: 'ftt' },
    { id: 'leo-token', name: 'LEO Token', symbol: 'leo' },
    { id: 'bitcoin-cash', name: 'Bitcoin Cash', symbol: 'bch' },
    { id: 'okb', name: 'OKB', symbol: 'okb' },
    { id: 'algorand', name: 'Algorand', symbol: 'algo' },
    { id: 'stellar', name: 'Stellar', symbol: 'xlm' },
    { id: 'uniswap', name: 'Uniswap', symbol: 'uni' },
    { id: 'hedera-hashgraph', name: 'Hedera', symbol: 'hbar' },
    { id: 'axie-infinity', name: 'Axie Infinity', symbol: 'axs' },
    { id: 'decentraland', name: 'Decentraland', symbol: 'mana' },
    { id: 'the-sandbox', name: 'The Sandbox', symbol: 'sand' },
    { id: 'ethereum-classic', name: 'Ethereum Classic', symbol: 'etc' },
    { id: 'internet-computer', name: 'Internet Computer', symbol: 'icp' },
    { id: 'elrond-erd-2', name: 'Elrond', symbol: 'egld' },
    { id: 'monero', name: 'Monero', symbol: 'xmr' },
    { id: 'compound-ether', name: 'cETH', symbol: 'ceth' },
    { id: 'vechain', name: 'VeChain', symbol: 'vet' },
    { id: 'fantom', name: 'Fantom', symbol: 'ftm' },
    { id: 'filecoin', name: 'Filecoin', symbol: 'fil' },
    { id: 'klay-token', name: 'Klaytn', symbol: 'klay' },
    { id: 'osmosis', name: 'Osmosis', symbol: 'osmo' },
    { id: 'frax', name: 'Frax', symbol: 'frax' },
    { id: 'theta-token', name: 'Theta Network', symbol: 'theta' },
    { id: 'magic-internet-money', name: 'Magic Internet Money', symbol: 'mim' },
    { id: 'waves', name: 'Waves', symbol: 'waves' },
    { id: 'tezos', name: 'Tezos', symbol: 'xtz' },
    { id: 'the-graph', name: 'The Graph', symbol: 'grt' },
    { id: 'thorchain', name: 'THORChain', symbol: 'rune' },
    { id: 'compound-usd-coin', name: 'cUSDC', symbol: 'cusdc' },
    { id: 'helium', name: 'Helium', symbol: 'hnt' },
    { id: 'eos', name: 'EOS', symbol: 'eos' },
    { id: 'flow', name: 'Flow', symbol: 'flow' },
    { id: 'iota', name: 'IOTA', symbol: 'miota' },
    { id: 'ecomi', name: 'ECOMI', symbol: 'omi' },
    { id: 'zcash', name: 'Zcash', symbol: 'zec' },
    { id: 'cdai', name: 'cDAI', symbol: 'cdai' },
    { id: 'theta-fuel', name: 'Theta Fuel', symbol: 'tfuel' },
    { id: 'aave', name: 'Aave', symbol: 'aave' },
    { id: 'juno-network', name: 'JUNO', symbol: 'juno' },
    { id: 'maker', name: 'Maker', symbol: 'mkr' },
    { id: 'gala', name: 'Gala', symbol: 'gala' },
    { id: 'bittorrent', name: 'BitTorrent', symbol: 'btt' },
    { id: 'arweave', name: 'Arweave', symbol: 'ar' },
    { id: 'huobi-btc', name: 'Huobi BTC', symbol: 'hbtc' },
    { id: 'pancakeswap-token', name: 'PancakeSwap', symbol: 'cake' },
    { id: 'quant-network', name: 'Quant', symbol: 'qnt' },
    { id: 'harmony', name: 'Harmony', symbol: 'one' },
    { id: 'ecash', name: 'eCash', symbol: 'xec' },
    { id: 'bitcoin-cash-sv', name: 'Bitcoin SV', symbol: 'bsv' },
    { id: 'neo', name: 'NEO', symbol: 'neo' },
    { id: 'celo', name: 'Celo', symbol: 'celo' },
    { id: 'true-usd', name: 'TrueUSD', symbol: 'tusd' },
    { id: 'huobi-token', name: 'Huobi Token', symbol: 'ht' },
    { id: 'kucoin-shares', name: 'KuCoin Token', symbol: 'kcs' },
    { id: 'celsius-degree-token', name: 'Celsius Network', symbol: 'cel' },
    { id: 'blockstack', name: 'Stacks', symbol: 'stx' },
    { id: 'humans-ai', name: 'Humans.ai', symbol: 'heart' },
    { id: 'enjincoin', name: 'Enjin Coin', symbol: 'enj' },
    { id: 'basic-attention-token', name: 'Basic Attention Token', symbol: 'bat' },
    { id: 'nexo', name: 'NEXO', symbol: 'nexo' },
    { id: 'radix', name: 'Radix', symbol: 'xrd' },
    { id: 'amp-token', name: 'Amp', symbol: 'amp' },
    { id: 'kusama', name: 'Kusama', symbol: 'ksm' },
    { id: 'chiliz', name: 'Chiliz', symbol: 'chz' },
    { id: 'kadena', name: 'Kadena', symbol: 'kda' },
    { id: 'dash', name: 'Dash', symbol: 'dash' },
    { id: 'xido-finance', name: 'Xido Finance', symbol: 'xido' },
    { id: 'frax-share', name: 'Frax Share', symbol: 'fxs' },
    { id: 'bitdao', name: 'BitDAO', symbol: 'bit' },
    { id: 'paxos-standard', name: 'Pax Dollar', symbol: 'usdp' },
    { id: 'convex-finance', name: 'Convex Finance', symbol: 'cvx' },
    { id: 'gatechain-token', name: 'GateToken', symbol: 'gt' },
    { id: 'loopring', name: 'Loopring', symbol: 'lrc' },
    { id: 'havven', name: 'Synthetix Network Token', symbol: 'snx' },
    { id: 'nem', name: 'NEM', symbol: 'xem' },
    { id: 'curve-dao-token', name: 'Curve DAO Token', symbol: 'crv' },
    { id: 'anchor-protocol', name: 'Anchor Protocol', symbol: 'anc' },
    { id: 'secret', name: 'Secret', symbol: 'scrt' },
    { id: 'oasis-network', name: 'Oasis Network', symbol: 'rose' },
    { id: 'link', name: 'LINK', symbol: 'ln' },
    { id: 'compound-usdt', name: 'cUSDT', symbol: 'cusdt' },
    { id: 'mina-protocol', name: 'Mina Protocol', symbol: 'mina' },
    { id: 'decred', name: 'Decred', symbol: 'dcr' },
    { id: 'compound-governance-token', name: 'Compound', symbol: 'comp' },
    { id: 'holotoken', name: 'Holo', symbol: 'hot' },
    { id: 'iotex', name: 'IoTeX', symbol: 'iotx' },
    { id: 'bitkub-coin', name: 'Bitkub Coin', symbol: 'kub' },
    { id: 'neutrino', name: 'Neutrino USD', symbol: 'usdn' },
    { id: 'yearn-finance', name: 'yearn.finance', symbol: 'yfi' },
    { id: 'smooth-love-potion', name: 'Smooth Love Potion', symbol: 'slp' },
    { id: 'xdce-crowd-sale', name: 'XDC Network', symbol: 'xdc' },
    { id: 'nxm', name: 'Nexus Mutual', symbol: 'nxm' },
    { id: 'qtum', name: 'Qtum', symbol: 'qtum' },
    { id: 'wax', name: 'WAX', symbol: 'waxp' },
    { id: 'pax-gold', name: 'PAX Gold', symbol: 'paxg' },
    { id: '1inch', name: '1inch', symbol: '1inch' },
    { id: 'sushi', name: 'Sushi', symbol: 'sushi' },
    { id: 'renbtc', name: 'renBTC', symbol: 'renbtc' },
    { id: 'pocket-network', name: 'Pocket Network', symbol: 'pokt' },
    { id: 'livepeer', name: 'Livepeer', symbol: 'lpt' },
    { id: 'msol', name: 'Marinade staked SOL', symbol: 'msol' },
    { id: 'ankr', name: 'Ankr', symbol: 'ankr' },
    { id: 'render-token', name: 'Render Token', symbol: 'rndr' },
    { id: 'bancor', name: 'Bancor Network Token', symbol: 'bnt' },
    { id: 'omisego', name: 'OMG Network', symbol: 'omg' },
    { id: 'zilliqa', name: 'Zilliqa', symbol: 'zil' },
    { id: 'gnosis', name: 'Gnosis', symbol: 'gno' },
    { id: 'fei-usd', name: 'Fei USD', symbol: 'fei' },
    { id: 'icon', name: 'ICON', symbol: 'icx' },
    { id: 'ravencoin', name: 'Ravencoin', symbol: 'rvn' },
    { id: 'safemoon-2', name: 'SafeMoon', symbol: 'sfm' },
    { id: 'iostoken', name: 'IOST', symbol: 'iost' },
    { id: 'bitcoin-gold', name: 'Bitcoin Gold', symbol: 'btg' },
    { id: 'uma', name: 'UMA', symbol: 'uma' },
    { id: 'kava', name: 'Kava', symbol: 'kava' },
    { id: 'oec-token', name: 'OEC Token', symbol: 'okt' },
    { id: 'songbird', name: 'Songbird', symbol: 'sgb' },
    { id: 'woo-network', name: 'WOO Network', symbol: 'woo' },
    { id: 'e-radix', name: 'e-Radix', symbol: 'exrd' },
    { id: 'moonbeam', name: 'Moonbeam', symbol: 'glmr' },
    { id: 'velas', name: 'Velas', symbol: 'vlx' },
    { id: 'tether-gold', name: 'Tether Gold', symbol: 'xaut' },
    { id: 'sapphire', name: 'Sapphire', symbol: 'sapp' },
    { id: 'rocket-pool', name: 'Rocket Pool', symbol: 'rpl' },
    { id: 'zencash', name: 'Horizen', symbol: 'zen' },
    { id: 'rally-2', name: 'Rally', symbol: 'rly' },
    { id: 'liquity-usd', name: 'Liquity USD', symbol: 'lusd' },
    { id: 'golem', name: 'Golem', symbol: 'glm' },
    { id: 'baby-doge-coin', name: 'Baby Doge Coin', symbol: 'babydoge' },
    { id: 'audius', name: 'Audius', symbol: 'audio' },
    { id: 'metis-token', name: 'Metis Token', symbol: 'metis' },
    { id: 'siacoin', name: 'Siacoin', symbol: 'sc' },
    { id: 'ontology', name: 'Ontology', symbol: 'ont' },
    { id: '0x', name: '0x', symbol: 'zrx' },
    { id: 'apenft', name: 'APENFT', symbol: 'nft' },
    { id: 'dydx', name: 'dYdX', symbol: 'dydx' },
    { id: 'swissborg', name: 'SwissBorg', symbol: 'chsb' },
    { id: 'skale', name: 'SKALE', symbol: 'skl' },
    { id: 'synapse-2', name: 'Synapse', symbol: 'syn' },
    { id: 'dogelon-mars', name: 'Dogelon Mars', symbol: 'elon' },
    { id: 'stepn', name: 'STEPN', symbol: 'gmt' },
    { id: 'olympus', name: 'Olympus', symbol: 'ohm' },
    { id: 'constellation-labs', name: 'Constellation', symbol: 'dag' },
    { id: 'immutable-x', name: 'Immutable X', symbol: 'imx' },
    { id: 'convex-crv', name: 'Convex CRV', symbol: 'cvxcrv' },
    { id: 'gemini-dollar', name: 'Gemini Dollar', symbol: 'gusd' },
    { id: 'just', name: 'JUST', symbol: 'jst' },
    { id: 'polymath', name: 'Polymath', symbol: 'poly' },
    { id: 'nucypher', name: 'NuCypher', symbol: 'nu' },
    { id: 'keep-network', name: 'Keep Network', symbol: 'keep' },
    { id: 'everdome', name: 'Everdome', symbol: 'dome' },
    { id: 'lido-dao', name: 'Lido DAO', symbol: 'ldo' },
    { id: 'hive', name: 'Hive', symbol: 'hive' },
    { id: 'bitclout', name: 'Decentralized Social', symbol: 'deso' },
    { id: 'illuvium', name: 'Illuvium', symbol: 'ilv' },
    { id: 'republic-protocol', name: 'REN', symbol: 'ren' },
    { id: 'zelcash', name: 'Flux', symbol: 'flux' },
    { id: 'nervos-network', name: 'Nervos Network', symbol: 'ckb' },
    { id: 'spell-token', name: 'Spell Token', symbol: 'spell' },
    { id: 'constitutiondao', name: 'ConstitutionDAO', symbol: 'people' },
    { id: 'defi-kingdoms', name: 'DeFi Kingdoms', symbol: 'jewel' },
    { id: 'ultra', name: 'Ultra', symbol: 'uos' },
    { id: 'husd', name: 'HUSD', symbol: 'husd' },
    { id: 'tomb', name: 'Tomb', symbol: 'tomb' },
    { id: 'flex-coin', name: 'FLEX Coin', symbol: 'flex' },
    { id: 'looksrare', name: 'LooksRare', symbol: 'looks' },
    { id: 'telcoin', name: 'Telcoin', symbol: 'tel' },
    { id: 'kyber-network-crystal', name: 'Kyber Network Crystal', symbol: 'knc' },
    { id: 'digitalbits', name: 'DigitalBits', symbol: 'xdb' },
    { id: 'lisk', name: 'Lisk', symbol: 'lsk' },
    { id: 'tenset', name: 'Tenset', symbol: '10set' },
    { id: 'digibyte', name: 'DigiByte', symbol: 'dgb' },
    { id: 'syscoin', name: 'Syscoin', symbol: 'sys' },
    { id: 'playdapp', name: 'PlayDapp', symbol: 'pla' }
];