export const coinsList = [
    'Bitcoin',
    'Ethereum',
    'Tether',
    'BNB',
    'USD Coin',
    'XRP',
    'Terra',
    'Solana',
    'Cardano',
    'Polkadot',
    'Avalanche',
    'Binance USD',
    'Dogecoin',
    'TerraUSD',
    'Shiba Inu',
    'Wrapped Bitcoin',
    'Cronos',
    'Polygon',
    'Dai',
    'Cosmos Hub',
    'Litecoin',
    'Lido Staked Ether',
    'Near',
    'Chainlink',
    'TRON',
    'FTX Token',
    'LEO Token',
    'Bitcoin Cash',
    'OKB',
    'Algorand',
    'Stellar',
    'Uniswap',
    'Hedera',
    'Axie Infinity',
    'Elrond',
    'Decentraland',
    'Ethereum Classic',
    'Monero',
    'Internet Computer',
    'The Sandbox',
    'cETH',
    'VeChain',
    'Fantom',
    'Filecoin',
    'Klaytn',
    'Osmosis',
    'Waves',
    'Frax',
    'Magic Internet Money',
    'Theta Network',
    'Tezos',
    'The Graph',
    'cUSDC',
    'Helium',
    'THORChain',
    'EOS',
    'IOTA',
    'cDAI',
    'ECOMI',
    'Flow',
    'Theta Fuel',
    'Zcash',
    'Aave',
    'JUNO',
    'BitTorrent',
    'Gala',
    'Arweave',
    'Maker',
    'Huobi BTC',
    'PancakeSwap',
    'Quant',
    'eCash',
    'Harmony',
    'Bitcoin SV',
    'TrueUSD',
    'KuCoin Token',
    'NEO',
    'Huobi Token',
    'Humans.ai',
    'Stacks',
    'Celsius Network',
    'Enjin Coin',
    'NEXO',
    'Basic Attention Token',
    'Amp',
    'Radix',
    'Kusama',
    'Celo',
    'Kadena',
    'Chiliz',
    'Frax Share',
    'Dash',
    'Pax Dollar',
    'BitDAO',
    'GateToken',
    'Convex Finance',
    'NEM',
    'Loopring',
    'Synthetix Network Token',
    'Xido Finance'
];